/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bed.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/Bed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Headboard1_Narra.geometry}
				material={materials["Material.004"]}
				position={[-0.013, 1.722, -2.032]}
				rotation={[1.571, 0.008, 3.136]}
			/>
			<mesh
				geometry={nodes.Bed1_Leg1_Narra.geometry}
				material={materials.Material}
				position={[0.946, 0.358, -1.936]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-0.079, -0.309, -0.089]}
			/>
			<mesh
				geometry={nodes.Headboard2_Narra.geometry}
				material={materials["Material.008"]}
				position={[-0.213, -0.878, -2.026]}
				scale={[0.745, 0.691, 0.836]}
			/>
			<mesh
				geometry={nodes.Bed2_Leg2_Narra.geometry}
				material={materials["Material.012"]}
				position={[0.967, 0.336, -1.92]}
				scale={[0.088, 0.279, 0.08]}
			/>
			<mesh
				geometry={nodes.Bed1_Leg1_Mahogany.geometry}
				material={materials["Material.001"]}
				position={[3.621, 0.362, -1.936]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-0.079, -0.309, -0.089]}
			/>
			<mesh
				geometry={nodes.Bed1_Leg1_Brown.geometry}
				material={materials["Material.002"]}
				position={[6.304, 0.369, -1.936]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-0.079, -0.309, -0.089]}
			/>
			<mesh
				geometry={nodes.Bed1_Leg1_Acacia.geometry}
				material={materials["Material.003"]}
				position={[8.964, 0.366, -1.936]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-0.079, -0.309, -0.089]}
			/>
			<mesh
				geometry={nodes.Headboard1_Mahogany.geometry}
				material={materials["Material.005"]}
				position={[2.662, 1.724, -2.03]}
				rotation={[1.571, 0.008, 3.136]}
			/>
			<mesh
				geometry={nodes.Headboard1_Brown.geometry}
				material={materials["Material.006"]}
				position={[5.349, 1.724, -2.029]}
				rotation={[1.571, 0.008, 3.136]}
			/>
			<mesh
				geometry={nodes.Headboard1_Acacia.geometry}
				material={materials["Material.007"]}
				position={[8.006, 1.724, -2.032]}
				rotation={[1.571, 0.008, 3.136]}
			/>
			<mesh
				geometry={nodes.Headboard2_Mahogany.geometry}
				material={materials["Material.009"]}
				position={[2.455, -0.878, -2.029]}
				scale={[0.745, 0.691, 0.836]}
			/>
			<mesh
				geometry={nodes.Headboard2_Brown.geometry}
				material={materials["Material.010"]}
				position={[5.144, -0.878, -2.027]}
				scale={[0.745, 0.691, 0.836]}
			/>
			<mesh
				geometry={nodes.Headboard2_Acacia.geometry}
				material={materials["Material.011"]}
				position={[7.798, -0.878, -2.031]}
				scale={[0.745, 0.691, 0.836]}
			/>
			<mesh
				geometry={nodes.Bed2_Leg2_Mahogany.geometry}
				material={materials["Material.013"]}
				position={[3.626, 0.336, -1.908]}
				scale={[0.088, 0.279, 0.08]}
			/>
			<mesh
				geometry={nodes.Bed2_Leg2_Brown.geometry}
				material={materials["Material.014"]}
				position={[6.316, 0.336, -1.908]}
				scale={[0.088, 0.279, 0.08]}
			/>
			<mesh
				geometry={nodes.Bed2_Leg2_Acacia.geometry}
				material={materials["Material.015"]}
				position={[8.963, 0.336, -1.912]}
				scale={[0.088, 0.279, 0.08]}
			/>
		</group>
	);
}

useGLTF.preload("/Bed.glb");
