/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ChairModels.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Chair({ selectedBackrest, selectedSeat, selectedWood }) {
	const { nodes, materials } = useGLTF("/Models/ChairModels.glb");

	const getBackrestNode = () => {
		switch (selectedBackrest) {
			case "Design 1":
				return {
					geometry: nodes.BackRestD1.geometry,
					material: materials["Brown "],
					position: [0.07, 0.859, 0.88],
				};
			case "Design 2":
				return {
					geometry: nodes.BackRestD2.geometry,
					material: materials["Brown "],
					position: [0.07, 0.859, 0.88],
				};
			case "Design 3":
				return {
					geometry: nodes.BackRestD3.geometry,
					material: materials["Brown "],
					position: [0.07, 0.859, 0.88],
				};
			case "Design 4":
				return {
					geometry: nodes.BackRestD4.geometry,
					material: materials["Brown "],
					position: [0.07, 0.859, 0.88],
				};
			default:
				return {
					geometry: nodes.Back_Rest.geometry,
					material: materials["Brown "],
					position: [0.07, 0.859, 0.88],
				};
		}
	};

	// Function to get the appropriate seat node and material based on selection
	const getSeatNode = () => {
		switch (selectedSeat) {
			case "Design 1":
				return {
					geometry: nodes.ChairSeatD1.geometry,
					material: materials["Brown "],
					position: [0, -0.119, 0],
					scale: [1.2, 0.066, 1.2],
				};
			case "Design 2":
				return {
					geometry: nodes.ChairSeatD2.geometry,
					material: materials["Brown "],
					position: [0, -0.119, 0],
					scale: [1.2, 0.066, 1.2],
				};
			case "Design 3":
				return {
					geometry: nodes.ChairSeatD3.geometry,
					material: materials["Brown "],
					position: [0, -0.119, 0],
					scale: [1.2, 0.066, 1.2],
				};
			case "Design 4":
				return {
					geometry: nodes.ChairSeatD4.geometry,
					material: materials["Brown "],
					position: [0, -0.119, 0],
					scale: [1.2, 0.066, 1.2],
				};
			default:
				return {
					geometry: nodes.Chair_Seat.geometry,
					material: materials["Brown "],
					position: [0, -0.119, 0],
					scale: [1.2, 0.066, 1.2],
				};
		}
	};

	// Get the appropriate nodes and materials
	const backrest = getBackrestNode();
	const seat = getSeatNode();

	// return (
	// 	<group dispose={null}>
	// 		<mesh
	// 			geometry={nodes.Chair_Seat.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0, -0.119, 0]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Back_Rest.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0.07, 0.859, 0.88]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD1.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0.08, 0.854, 0.871]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD2.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0.07, 0.859, 0.88]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD3.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0.081, 0.878, 0.783]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD4.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0.07, 0.859, 0.88]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD1.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0, -0.119, 0]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD2.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0, -0.119, 0]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD3.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0, -0.119, 0]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD4.geometry}
	// 			material={materials["Brown "]}
	// 			position={[0, -0.119, 0]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Legs.geometry}
	// 			material={materials["Brown "]}
	// 			position={[-0.847, -0.269, -0.89]}
	// 			scale={0.175}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD1mahogany.geometry}
	// 			material={materials["Mahogany.003"]}
	// 			position={[3.118, 0.88, 0.882]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Seatmahogany.geometry}
	// 			material={materials["Mahogany.002"]}
	// 			position={[3.046, -0.159, 0.034]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Legsmahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[2.147, -0.388, -0.735]}
	// 			scale={0.175}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD1acacia.geometry}
	// 			material={materials["Acacia.002"]}
	// 			position={[5.951, 0.842, 0.901]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Seatacacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.902, -0.117, 0.075]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Legsacacia.geometry}
	// 			material={materials.Acacia}
	// 			position={[5.031, -0.304, -0.863]}
	// 			scale={0.175}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD1narra.geometry}
	// 			material={materials["Narra.001"]}
	// 			position={[9.382, 0.771, 1.03]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Seatnarra.geometry}
	// 			material={materials["Narra.003"]}
	// 			position={[9.333, -0.188, 0.204]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Chair_Legsnarra.geometry}
	// 			material={materials.Narra}
	// 			position={[8.462, -0.376, -0.735]}
	// 			scale={0.175}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Back_Restmahogany.geometry}
	// 			material={materials["Mahogany.001"]}
	// 			position={[3.107, 0.877, 0.96]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD1mahogany.geometry}
	// 			material={materials["Mahogany.001"]}
	// 			position={[3.037, -0.1, 0.08]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Back_Restacacia.geometry}
	// 			material={materials.Acacia}
	// 			position={[6.054, 0.941, 0.849]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD1acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.983, -0.037, -0.031]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.Back_Restnarra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.44, 0.875, 0.937]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD1narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.369, -0.103, 0.057]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD2mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[2.906, -0.119, -0.081]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD2acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.883, -0.038, -0.118]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD2narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.311, -0.096, -0.154]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD2mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[3.003, 0.931, 0.731]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD2acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.917, 0.948, 0.731]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD2narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.388, 0.899, 0.731]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD3mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[3.072, 0.871, 0.706]}
	// 			rotation={[-1.613, 0, 0]}
	// 			scale={0.982}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD3mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[2.972, -0.092, -0.002]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD3acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[6.037, 0.95, 0.606]}
	// 			rotation={[-1.613, 0, 0]}
	// 			scale={0.982}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD3acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.997, -0.054, -0.11]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD3narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.411, 0.888, 0.779]}
	// 			rotation={[-1.613, 0, 0]}
	// 			scale={0.982}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD3narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.363, -0.096, 0.074]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD4mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[3.014, 0.856, 0.96]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD4mahogany.geometry}
	// 			material={materials.Mahogany}
	// 			position={[2.98, -0.146, 0.062]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD4acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.989, 0.882, 0.956]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD4acacia.geometry}
	// 			material={materials.Aacia}
	// 			position={[5.955, -0.12, 0.058]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.BackRestD4narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.414, 0.91, 0.867]}
	// 			rotation={[-1.613, 0, 0]}
	// 		/>
	// 		<mesh
	// 			geometry={nodes.ChairSeatD4narra.geometry}
	// 			material={materials.Narra}
	// 			position={[9.38, -0.092, -0.031]}
	// 			scale={[1.2, 0.066, 1.2]}
	// 		/>
	// 	</group>
	// );

	return (
		<group dispose={null}>
			{selectedWood === "Acacia" ? (
				<>
					{/* Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={materials.Acacia}
						position={[0.07, 0.859, 0.88]}
						rotation={[-1.613, 0, 0]}
					/>

					{/* chair shit */}
					<mesh
						geometry={seat.geometry}
						material={materials.Aacia}
						position={[0, -0.119, 0]}
						scale={[1.2, 0.066, 1.2]}
					/>

					{/* Legs */}
					<mesh
						geometry={nodes.Chair_Legsacacia.geometry}
						material={materials.Acacia}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			) : (
				<>
					{/* Dynamic Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={backrest.material}
						position={backrest.position}
						rotation={[-1.613, 0, 0]}
					/>
					<mesh
						geometry={seat.geometry}
						material={seat.material}
						position={seat.position}
						scale={seat.scale}
					/>
					<mesh
						geometry={nodes.Chair_Legs.geometry}
						material={materials["Brown "]}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			)}

			{selectedWood === "Mahogany" ? (
				<>
					{/* Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={materials.Mahogany}
						position={[0.07, 0.859, 0.88]}
						rotation={[-1.613, 0, 0]}
					/>

					{/* chair shit */}
					<mesh
						geometry={seat.geometry}
						material={materials.Mahogany}
						position={[0, -0.119, 0]}
						scale={[1.2, 0.066, 1.2]}
					/>

					{/* Legs */}
					<mesh
						geometry={nodes.Chair_Legsacacia.geometry}
						material={materials.Mahogany}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			) : (
				<>
					{/* Dynamic Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={backrest.material}
						position={backrest.position}
						rotation={[-1.613, 0, 0]}
					/>
					<mesh
						geometry={seat.geometry}
						material={seat.material}
						position={seat.position}
						scale={seat.scale}
					/>
					<mesh
						geometry={nodes.Chair_Legs.geometry}
						material={materials["Brown "]}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			)}

{selectedWood === "Narra" ? (
				<>
					{/* Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={materials.Narra}
						position={[0.07, 0.859, 0.88]}
						rotation={[-1.613, 0, 0]}
					/>

					{/* chair shit */}
					<mesh
						geometry={seat.geometry}
						material={materials.Narra}
						position={[0, -0.119, 0]}
						scale={[1.2, 0.066, 1.2]}
					/>

					{/* Legs */}
					<mesh
						geometry={nodes.Chair_Legsacacia.geometry}
						material={materials.Narra}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			) : (
				<>
					{/* Dynamic Backrest */}
					<mesh
						geometry={backrest.geometry}
						material={backrest.material}
						position={backrest.position}
						rotation={[-1.613, 0, 0]}
					/>
					<mesh
						geometry={seat.geometry}
						material={seat.material}
						position={seat.position}
						scale={seat.scale}
					/>
					<mesh
						geometry={nodes.Chair_Legs.geometry}
						material={materials["Brown "]}
						position={[-0.847, -0.269, -0.89]}
						scale={0.175}
					/>
				</>
			)}
		</group>
	);
}

useGLTF.preload("/ChairModels.glb");
