/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DesignSofa.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Sofa({ selectedBackrest, selectedArmrest }) {
	const { nodes, materials } = useGLTF("/Models/DesignSofa.glb");

	const getBackrest = () => {
		switch (selectedBackrest) {
			case "Design 1":
				return {
					geometry: nodes.Backrest1.geometry,
					material: materials.Brown,
					// position: [0.145, 0.268, -1.188],
					// scale: [1.0, 0.7, 0.7],
					position: [0.145, 0.268, -1.188],
					scale: [0.84, 0.579, 0.632],
				};

			case "Design 2":
				return {
					geometry: nodes.Backrest2.geometry,
					material: materials.Brown,
					position: [-0.07, 0.063, -1.235],
					scale: [1.288, 1, 1.282],
				};

			case "Design 3":
				return {
					geometry: nodes.Backrest3.geometry,
					material: materials.Brown,
					position: [-1.839, 3.436, -1.145],
					scale: [1.389, 1, 1],
				};
			case "Design 4":
				return {
					geometry: nodes.Backrest4.geometry,
					material: materials.Brown,
					position: [-0.444, 0.75, -1.193],
					rotation: [1.453, Math.PI / 2, 0],
					scale: [0.008, 0.001, 0.008],
				};
			default:
				return {
					geometry: nodes.Backrest1.geometry,
					material: materials.Brown,
					position: [0.145, 0.268, -1.188],
					scale: [0.84, 0.579, 0.632],
				};
		}
	};

	const getArmrest = () => {
		switch (selectedArmrest) {
			case "Design 1":
				return {
					geometry: nodes.Armrest1.geometry,
					material: materials.Brown,
					position: [1.876, 0.425, 0],
					rotation: [0, 0, -0.014],
					scale: [0.71, 0.781, 1.141],
				};
			case "Design 2":
				return {
					geometry: nodes.Armrest2_.geometry,
					material: materials.Brown,
					position: [-0.499, 0.912, -1.203],
					rotation: [-1.571, 1.568, 3.023],
					scale: [0.008, 0.001, 0.008],
				};
			default:
				return {
					geometry: nodes.Armrest1.geometry,
					material: materials.Brown,
					position: [1.876, 0.425, 0],
					scale: [0.71, 0.781, 1.141],
				};
		}
	};

	const backrest = getBackrest();
	const armrest = getArmrest();

	return (
		<group dispose={null}>
			{/* <mesh
				geometry={nodes.Armrest1mahogany.geometry}
				material={materials.Material}
				position={[1.99, 0.512, 0]}
				rotation={[0, 0, -0.014]}
				scale={[0.71, 0.781, 1.141]}
			/>
			<mesh
				geometry={nodes["Backrest1,mahogany"].geometry}
				material={materials.Mahogany}
				position={[0.264, 0.303, -1.191]}
				scale={[0.842, 0.579, 0.632]}
			/>
			<mesh
				geometry={nodes.Backrest2mahogany.geometry}
				material={materials["Mahogany.001"]}
				position={[0.048, 0.11, -1.216]}
				rotation={[0, 0.002, 0.004]}
				scale={[1.29, 1, 1.282]}
			/>
			<mesh
				geometry={nodes.Backrest3mahogany.geometry}
				material={materials["Mahogany.002"]}
				position={[-1.673, 3.483, -1.174]}
				scale={[1.338, 1, 1]}
			/>
			<mesh
				geometry={nodes.Backrest4mahogany.geometry}
				material={materials["Mahogany.001"]}
				position={[-0.33, 0.775, -1.21]}
				rotation={[1.453, Math.PI / 2, 0]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Armrest2mahogany.geometry}
				material={materials["Mahogany.001"]}
				position={[-0.376, 0.949, -1.205]}
				rotation={[-1.571, 1.568, 3.023]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Backrest4acacia.geometry}
				material={materials["Acacia.001"]}
				position={[-4.05, 0.787, -1.207]}
				rotation={[1.453, Math.PI / 2, 0]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Armrest2acacia.geometry}
				material={materials["Acacia.001"]}
				position={[-4.093, 0.955, -1.181]}
				rotation={[-1.571, 1.568, 3.023]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Backrest4narra.geometry}
				material={materials["Narra.001"]}
				position={[-7.694, 0.784, -1.217]}
				rotation={[1.453, Math.PI / 2, 0]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Armrest2narra.geometry}
				material={materials.Narra}
				position={[-7.736, 0.952, -1.191]}
				rotation={[-1.571, 1.568, 3.023]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Backrest2acacia.geometry}
				material={materials["Acacia.002"]}
				position={[-3.671, 0.094, -1.231]}
				rotation={[0.018, 0.001, 0.008]}
				scale={[1.288, 1, 1.282]}
			/>
			<mesh
				geometry={nodes.Backrest2narra.geometry}
				material={materials["Narra.001"]}
				position={[-7.319, 0.107, -1.206]}
				rotation={[0, 0.002, 0.014]}
				scale={[1.286, 1, 1.282]}
			/>
			<mesh
				geometry={nodes.Backrest3acacia.geometry}
				material={materials["Acacia.003"]}
				position={[-5.336, 3.477, -1.145]}
				scale={[1.317, 1, 1]}
			/>
			<mesh
				geometry={nodes.Backrest3narra.geometry}
				material={materials["Narra.002"]}
				position={[-9.041, 3.477, -1.174]}
				scale={[1.338, 1, 1]}
			/>
			<mesh
				geometry={nodes.Backrest1acacia.geometry}
				material={materials.Acacia}
				position={[-3.426, 0.297, -1.191]}
				scale={[0.84, 0.579, 0.632]}
			/>
			<mesh
				geometry={nodes.Backrest1narra.geometry}
				material={materials["Narra.003"]}
				position={[-7.096, 0.309, -1.191]}
				scale={[0.842, 0.579, 0.632]}
			/>
			<mesh
				geometry={nodes.Armrest1acacia.geometry}
				material={materials["Material.001"]}
				position={[-1.708, 0.464, 0]}
				rotation={[0, 0, -0.014]}
				scale={[0.71, 0.781, 1.141]}
			/>
			<mesh
				geometry={nodes.Armrest1narra.geometry}
				material={materials["Material.002"]}
				position={[-5.372, 0.495, 0]}
				rotation={[0, 0, -0.014]}
				scale={[0.71, 0.781, 1.141]}
			/>
			<mesh
				geometry={nodes.Armrest1.geometry}
				material={materials.Brown}
				position={[1.876, 0.425, 0]}
				rotation={[0, 0, -0.014]}
				scale={[0.71, 0.781, 1.141]}
			/>
			<mesh
				geometry={nodes.Backrest1.geometry}
				material={materials.Brown}
				position={[0.145, 0.268, -1.188]}
				scale={[0.84, 0.579, 0.632]}
			/>
			<mesh
				geometry={nodes.Backrest2.geometry}
				material={materials.Brown}
				position={[-0.07, 0.063, -1.235]}
				rotation={[0.018, 0.001, 0.008]}
				scale={[1.288, 1, 1.282]}
			/>
			<mesh
				geometry={nodes.Backrest3.geometry}
				material={materials.Brown}
				position={[-1.839, 3.436, -1.145]}
				scale={[1.389, 1, 1]}
			/>
			<mesh
				geometry={nodes.Backrest4.geometry}
				material={materials.Brown}
				position={[-0.444, 0.75, -1.193]}
				rotation={[1.453, Math.PI / 2, 0]}
				scale={[0.008, 0.001, 0.008]}
			/>
			<mesh
				geometry={nodes.Armrest2_.geometry}
				material={materials.Brown}
				position={[-0.499, 0.912, -1.203]}
				rotation={[-1.571, 1.568, 3.023]}
				scale={[0.008, 0.001, 0.008]}
			/> */}

			<mesh
				geometry={armrest.geometry}
				material={armrest.material}
				rotation={armrest.rotation}
				position={armrest.position}
				scale={armrest.scale}
			/>
			<mesh
				geometry={backrest.geometry}
				material={backrest.material}
				position={backrest.position}
				rotation={backrest.rotation}
				scale={backrest.scale}
			/>
		</group>
	);
}

useGLTF.preload("/Models/DesignSofa.glb");
