/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DesignDoor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Door({ selectedDoorDesign, selectedDoorWoodType }) {
	const { nodes, materials } = useGLTF("/Models/DesignDoor.glb");

	const getDoorDesign = () => {
		switch (selectedDoorDesign) {
			case "Design 1":
				return {
					geometry: nodes.DoorD1.geometry,
					material: materials.Brown,
					scale: [1.019, 1, 1],
				};
			case "Design 2":
				return {
					geometry: nodes.Door2.geometry,
					material: materials.Brown,
					scale: [1.019, 1, 1],
				};
			case "Design 3":
				return {
					geometry: nodes.Door3.geometry,
					material: materials.Brown,
					position: [0.008, 0, 0],
					scale: [1.013, 1, 1],
				};

			case "Design 4":
				return {
					geometry: nodes.Door4.geometry,
					material: materials.Brown,
					position: [0.017, 0, 0],
					scale: [1.019, 1, 1],
				};

			case "Design 5":
				return {
					geometry: nodes.Door5.geometry,
					material: materials.Brown,
					position: [0.001, 0, 0],
					scale: [1.017, 1, 1],
				};

			case "Design 6":
				return {
					geometry: nodes.Door6.geometry,
					material: materials.Brown,
					position: [-0.364, -0.012, 0.005],
					scale: [1.011, 1, 1],
				};

			case "Design 7":
				return {
					geometry: nodes.Door8.geometry,
					material: materials.Brown,
					position: [0.006, 0, 0],
					scale: [1.013, 1, 1],
				};

			default:
				return {
					geometry: nodes.DoorD1.geometry,
					material: materials.Brown,
					scale: [1.019, 1, 1],
				};
		}
	};

	const doorDesign = getDoorDesign();

	return (
		<group dispose={null}>
			{selectedDoorWoodType === "Acacia" ? (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={materials.Acacia}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Acacia}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			) : (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={doorDesign.material}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Brown}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			)}

			{selectedDoorWoodType === "Mahogany" ? (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={materials.Mahogany}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Mahogany}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			) : (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={doorDesign.material}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Brown}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			)}

			{selectedDoorWoodType === "Narra" ? (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={materials.Narra}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Narra}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			) : (
				<>
					<mesh
						geometry={doorDesign.geometry}
						material={doorDesign.material}
						position={doorDesign.position}
						scale={doorDesign.scale}
					/>
					<mesh
						geometry={nodes.DoorFrame.geometry}
						material={materials.Brown}
						position={[-0.959, -0.002, 0.004]}
						rotation={[0, 0, -Math.PI]}
						scale={[-0.047, -1.095, -0.07]}
					/>
				</>
			)}

			{/* 
			<mesh
				geometry={nodes.Door2.geometry}
				material={materials.Brown}
				scale={1.003}
			/>
			<mesh
				geometry={nodes.Door5.geometry}
				material={materials.Brown}
				position={[0.001, 0, 0]}
				scale={[1.017, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door6.geometry}
				material={materials.Brown}
				position={[-0.364, -0.012, 0.005]}
				scale={1.011}
			/>
			<mesh
				geometry={nodes.Door8.geometry}
				material={materials.Brown}
				position={[0.006, 0, 0]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door4.geometry}
				material={materials.Brown}
				position={[0.017, 0, 0]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door3.geometry}
				material={materials.Brown}
				position={[0.008, 0, 0]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door2mahogany.geometry}
				material={materials.Mahogany}
				position={[1.317, -0.001, -0.023]}
				scale={1.003}
			/>
			<mesh
				geometry={nodes.DoorFramemahogany.geometry}
				material={materials.Mahogany}
				position={[0.358, -0.003, -0.019]}
				rotation={[0, 0, -Math.PI]}
				scale={[-0.047, -1.095, -0.07]}
			/>
			<mesh
				geometry={nodes.Door2acacia.geometry}
				material={materials.Acacia}
				position={[2.824, 0.009, -0.023]}
				scale={1.003}
			/>
			<mesh
				geometry={nodes.DoorFrameacacia.geometry}
				material={materials.Acacia}
				position={[1.865, 0.007, -0.019]}
				rotation={[0, 0, -Math.PI]}
				scale={[-0.047, -1.095, -0.07]}
			/>
			<mesh
				geometry={nodes.Door2narra.geometry}
				material={materials.Narra}
				position={[4.31, 0.03, -0.023]}
				scale={1.003}
			/>
			<mesh
				geometry={nodes.DoorFramenarra.geometry}
				material={materials.Narra}
				position={[3.351, 0.028, -0.019]}
				rotation={[0, 0, -Math.PI]}
				scale={[-0.047, -1.095, -0.07]}
			/>
			<mesh
				geometry={nodes.Door3mahogany.geometry}
				material={materials.Mahogany}
				position={[1.322, -0.008, -0.019]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door3acacia.geometry}
				material={materials.Acacia}
				position={[2.831, 0.016, -0.029]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door3narra.geometry}
				material={materials.Narra}
				position={[4.322, 0.039, -0.035]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door4mahogany.geometry}
				material={materials.Mahogany}
				position={[1.33, -0.011, 0]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door4acacia.geometry}
				material={materials.Acacia}
				position={[2.851, 0.003, -0.013]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door4narra.geometry}
				material={materials.Narra}
				position={[4.337, 0.015, -0.015]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door5mahogany.geometry}
				material={materials.Mahogany}
				position={[1.307, 0, -0.013]}
				scale={[1.017, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door5acacia.geometry}
				material={materials.Acacia}
				position={[2.814, 0.01, -0.014]}
				scale={[1.017, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door5narra.geometry}
				material={materials.Narra}
				position={[4.317, 0.027, -0.019]}
				scale={[1.017, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door6mahogany.geometry}
				material={materials.Mahogany}
				position={[0.958, 0.004, -0.025]}
				scale={1.011}
			/>
			<mesh
				geometry={nodes.Door6acacia.geometry}
				material={materials.Acacia}
				position={[2.447, 0.004, -0.025]}
				scale={1.011}
			/>
			<mesh
				geometry={nodes.Door6narra.geometry}
				material={materials.Narra}
				position={[3.931, 0.045, -0.035]}
				scale={1.011}
			/>
			<mesh
				geometry={nodes.DoorD1mahogany.geometry}
				material={materials.Mahogany}
				position={[1.312, 0, -0.02]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.DoorD1acacia.geometry}
				material={materials.Acacia}
				position={[2.826, 0.016, -0.014]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.DoorD1narra.geometry}
				material={materials.Narra}
				position={[4.315, 0.028, -0.023]}
				scale={[1.019, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door8mahogany.geometry}
				material={materials.Mahogany}
				position={[1.327, -0.012, -0.019]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door8acacia.geometry}
				material={materials.Acacia}
				position={[2.826, 0.013, 0.001]}
				scale={[1.013, 1, 1]}
			/>
			<mesh
				geometry={nodes.Door8narra.geometry}
				material={materials.Narra}
				position={[4.313, 0.018, -0.019]}
				scale={[1.013, 1, 1]}
			/> */}
		</group>
	);
}

useGLTF.preload("/Models/DesignDoor.glb");
