/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DoorModels.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Door({ selectedDesign }) {
	const { nodes, materials } = useGLTF("/Models/DoorModels.glb");

	const getDoorDesign = () => {
		switch (selectedDesign) {
			case 0:
				return {
					geometry: nodes.DoorD1.geometry,
					material: nodes.DoorD1.material,
					scale: [1.019, 1, 1],
				};
			case 1:
				return {
					geometry: nodes.Door2.geometry,
					material: nodes.Door2.material,
					scale: [1.019, 1, 1],
				};
			case 2:
				return {
					geometry: nodes.Door3.geometry,
					material: nodes.Door3.material,
					position: [0.008, 0, 0],
					scale: [1.013, 1, 1],
				};
			case 3:
				return {
					geometry: nodes.Door4.geometry,
					material: nodes.Door4.material,
					position: [0.017, 0, 0],
					scale: [1.019, 1, 1],
				};
			case 4:
				return {
					geometry: nodes.Door5.geometry,
					material: nodes.Door5.material,
					position: [0.001, 0, 0],
					scale: [1.017, 1, 1],
				};
			case 5:
				return {
					geometry: nodes.Door6.geometry,
					material: materials.Material ,
					position: [-0.364, -0.012, 0.005],
					scale: [1.017, 1, 1],
				};
			case 6:
				return {
					geometry: nodes.Door7.geometry,
					material: nodes.Door7.material,
					scale: [1.013, 1, 1],
				};
			case 7:
				return {
					geometry: nodes.Door8.geometry,
					material: nodes.Door8.material,
					position: [0.006, 0, 0],
					scale: [1.013, 1, 1],
				};
			default:
				return {
					geometry: nodes.Door1.geometry,
					material: nodes.Door1.material,
					scale: [1, 1, 1],
				};
		}
	};

	const doorDesign = getDoorDesign();

	return (
		<group dispose={null}>
			{/* Door frame */}
			<mesh
				geometry={nodes.DoorFrame.geometry}
				material={nodes.DoorFrame.material}
				position={[-0.959, -0.002, 0.004]}
				rotation={[0, 0, -Math.PI]}
				scale={[-0.047, -1.095, -0.07]}
			/>

			{/* Door design */}
			<mesh
				geometry={doorDesign.geometry}
				material={doorDesign.material}
				position={doorDesign.position || [0, 0, 0]}
				scale={doorDesign.scale || [1, 1, 1]}
			/>
		</group>
	);
}

useGLTF.preload("/Models/DoorModels.glb");
