/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Table.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/Table.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Table1_top1_Narra.geometry}
				material={materials["Material.004"]}
				position={[0.092, 3.077, 0.019]}
				rotation={[-Math.PI, 0, -Math.PI]}
				scale={[-2.843, -0.137, -6.388]}
			/>
			<mesh
				geometry={nodes.Table1_Leg1_Narra.geometry}
				material={materials.Material}
				position={[1.985, 2.721, -0.057]}
				rotation={[1.571, -0.001, -3.139]}
				scale={[0.245, 5.459, 0.23]}
			/>
			<mesh
				geometry={nodes.Table2_top2_Narra.geometry}
				material={materials["Material.008"]}
				position={[41.124, -18.302, -2.177]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[3.493, 3.493, 4.468]}
			/>
			<mesh
				geometry={nodes.Table3_top3_Narra.geometry}
				material={materials["Material.016"]}
				position={[0.053, 3.22, 0.047]}
				scale={[3.628, 1.39, 2.799]}
			/>
			<mesh
				geometry={nodes.Table2_Leg2_Narra.geometry}
				material={materials["Material.012"]}
				position={[0.064, 0.709, 0.096]}
				rotation={[-3.142, 1.567, 1.565]}
				scale={[-0.199, -5.55, -0.171]}
			/>
			<mesh
				geometry={nodes.Table1_Leg1_Mahogany.geometry}
				material={materials["Material.001"]}
				position={[1.985, 2.723, -13.587]}
				rotation={[1.571, -0.001, -3.139]}
				scale={[0.245, 5.459, 0.23]}
			/>
			<mesh
				geometry={nodes.Table1_Leg1_Brown.geometry}
				material={materials["Material.002"]}
				position={[1.985, 2.75, -26.776]}
				rotation={[1.571, -0.001, -3.139]}
				scale={[0.245, 5.459, 0.23]}
			/>
			<mesh
				geometry={nodes.Table1_Leg1_Acacia.geometry}
				material={materials["Material.003"]}
				position={[1.985, 2.756, -40.236]}
				rotation={[1.571, -0.001, -3.139]}
				scale={[0.245, 5.459, 0.23]}
			/>
			<mesh
				geometry={nodes.Table1_top1_Mahogany.geometry}
				material={materials["Material.005"]}
				position={[0.092, 3.001, -13.533]}
				rotation={[-Math.PI, 0, -Math.PI]}
				scale={[-2.843, -0.137, -6.388]}
			/>
			<mesh
				geometry={nodes.Table1_top1_Brown.geometry}
				material={materials["Material.006"]}
				position={[0.063, 2.976, -26.714]}
				rotation={[-Math.PI, 0, -Math.PI]}
				scale={[-2.843, -0.137, -6.388]}
			/>
			<mesh
				geometry={nodes.Table1_top1_Acacia.geometry}
				material={materials["Material.007"]}
				position={[0.122, 3.003, -40.074]}
				rotation={[-Math.PI, 0, -Math.PI]}
				scale={[-2.843, -0.137, -6.388]}
			/>
			<mesh
				geometry={nodes.Table2_top2_Mahogany.geometry}
				material={materials["Material.009"]}
				position={[41.139, -18.302, -15.547]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[3.493, 3.493, 4.468]}
			/>
			<mesh
				geometry={nodes.Table2_top2_Brown.geometry}
				material={materials["Material.010"]}
				position={[41.213, -18.302, -28.856]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[3.493, 3.493, 4.468]}
			/>
			<mesh
				geometry={nodes.Table2_top2_Acacia.geometry}
				material={materials["Material.011"]}
				position={[41.168, -18.302, -42.286]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[3.493, 3.493, 4.468]}
			/>
			<mesh
				geometry={nodes.Table2_Leg2_Mahogany.geometry}
				material={materials["Material.013"]}
				position={[0.064, 0.687, -13.439]}
				rotation={[3.142, 1.567, 1.565]}
				scale={[-0.195, -5.55, -0.171]}
			/>
			<mesh
				geometry={nodes.Table2_Leg2_Brown.geometry}
				material={materials["Material.014"]}
				position={[0.064, 0.667, -26.648]}
				rotation={[3.142, 1.567, 1.565]}
				scale={[-0.195, -5.55, -0.171]}
			/>
			<mesh
				geometry={nodes.Table2_Leg2_Acacia.geometry}
				material={materials["Material.015"]}
				position={[0.064, 0.667, -40.105]}
				rotation={[3.142, 1.567, 1.565]}
				scale={[-0.203, -5.55, -0.171]}
			/>
			<mesh
				geometry={nodes.Table3_top3_Mahogany.geometry}
				material={materials["Material.017"]}
				position={[0.053, 3.209, -13.46]}
				scale={[3.628, 1.39, 2.799]}
			/>
			<mesh
				geometry={nodes.Table3_top3_Brown.geometry}
				material={materials["Material.018"]}
				position={[-0.061, 3.202, -26.592]}
				scale={[3.628, 1.39, 2.799]}
			/>
			<mesh
				geometry={nodes.Table3_top3_Acacia.geometry}
				material={materials["Material.019"]}
				position={[-0.061, 3.199, -39.93]}
				scale={[3.628, 1.39, 2.799]}
			/>
		</group>
	);
}

useGLTF.preload("/Table.glb");
